package com.java.jsf.model.entities;

// Generated May 13, 2015 11:06:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblBank generated by hbm2java
 */
public class TblBank implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private String name;
	private Date modifyTime;
	private String status;
	private Boolean public_;

	public TblBank() {
	}

	public TblBank(String name, Date modifyTime, String status) {
		this.name = name;
		this.modifyTime = modifyTime;
		this.status = status;
	}

	public TblBank(String name, Date modifyTime, String status, Boolean public_) {
		this.name = name;
		this.modifyTime = modifyTime;
		this.status = status;
		this.public_ = public_;
	}

	public TblBank(int id, String name, Date modifyTime, String status,
			Boolean public_) {
		this.id = id;
		this.name = name;
		this.modifyTime = modifyTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Boolean getPublic_() {
		return this.public_;
	}

	public void setPublic_(Boolean public_) {
		this.public_ = public_;
	}

}
